using System.Text;
using ZeroAlloc.AsyncEvents.Generator.Models;

namespace ZeroAlloc.AsyncEvents.Generator.Writers;

internal static class AsyncEventWriter
{
    public static string Write(AsyncEventClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // The containing types, outermost first, then the class itself.
        var depth = model.Declarations.Count;
        for (var level = 0; level < depth; level++)
        {
            var open = Indent(level);
            sb.Append(open).AppendLine(model.Declarations[level]);
            sb.Append(open).AppendLine("{");
        }

        var member = Indent(depth);
        foreach (var field in model.Fields)
        {
            sb.Append(member).AppendLine("#pragma warning disable MA0046");
            sb.Append(member).AppendLine($"public event global::ZeroAlloc.AsyncEvents.AsyncEvent<{field.ArgTypeFqn}> {field.EventName}");
            sb.Append(member).AppendLine("{");
            sb.Append(member).AppendLine($"    add    => {field.FieldName}.Register(value);");
            sb.Append(member).AppendLine($"    remove => {field.FieldName}.Unregister(value);");
            sb.Append(member).AppendLine("}");
            sb.Append(member).AppendLine("#pragma warning restore MA0046");
            sb.AppendLine();
        }

        for (var level = depth - 1; level > 0; level--)
            sb.Append(Indent(level)).AppendLine("}");
        sb.Append("}");
        return sb.ToString();
    }

    private static string Indent(int level) => new(' ', level * 4);
}
