using System.Text;
using ZeroAlloc.AsyncEvents.Generator.Models;

namespace ZeroAlloc.AsyncEvents.Generator.Writers;

internal static class AsyncEventWriter
{
    public static string Write(AsyncEventClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.TypeName}");
        sb.AppendLine("{");

        foreach (var field in model.Fields)
        {
            sb.AppendLine("    #pragma warning disable MA0046");
            sb.AppendLine($"    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<{field.ArgTypeFqn}> {field.EventName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        add    => {field.FieldName}.Register(value);");
            sb.AppendLine($"        remove => {field.FieldName}.Unregister(value);");
            sb.AppendLine("    }");
            sb.AppendLine("    #pragma warning restore MA0046");
            sb.AppendLine();
        }

        sb.Append("}");
        return sb.ToString();
    }
}
