//HintName: MyService.AsyncEvents.g.cs
// <auto-generated/>
#nullable enable

partial class MyService
{
    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<string> OrderPlaced
    {
        add    => _orderPlaced.Register(value);
        remove => _orderPlaced.Unregister(value);
    }
    #pragma warning restore MA0046

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<int> ItemShipped
    {
        add    => _itemShipped.Register(value);
        remove => _itemShipped.Unregister(value);
    }
    #pragma warning restore MA0046

}